### ISSUE TITLE
Visualization class: FC/PSD/TS/etc.

### ISSUE THREAD

**Issue by tmorshed** [GriffithsLab/whobpyt#76]
Figure out the data structure.
- Physiological analytics

- Phase plane analysis
- PLS method

**Comment by Andrew-Clappison** [comment]
#101 was done
figure out if we want a plotting object or append as method to other object

**Comment by P-Oveisi** [comment]
We can approach it in two ways:
1. The visualization functions would be extra methods that we can add to data objects
2. We could define a visualization object which would take in the data obj to be plotted + the representation we want (e.g., time series, PSD, FC mat, etc.) and the viz object will do the plotting. 

I think the first option would make more sense if the data to be plotted isn't too complex. This would be similar to `mne.evoked.plot()` method in the MNE library.

In the case of more complex plots (for example 3D source localization) the second way would be more ideal. This is similar to the [Brain](https://mne.tools/stable/generated/mne.viz.Brain.html#mne-viz-brain) object in mne (`mne.viz.Brain`).

What are people's thoughts? How do you think we should proceed?

**Comment by Andrew-Clappison** [comment]
John Recommendation: For simpler figures taking only a few lines of code then write them explicitly in examples, for more complex plots with many lines then have them encapsulated in methods/functions

**Comment by Andrew-Clappison** [comment]
Current focus to improve the figures in eg 003r and eg 004r

**Comment by P-Oveisi** [comment]
Will make into MNE object to use MNE visualization funcitons. 

Can also add the montage data to use `.plot_joint()` more comprehensive plots.

**Comment by P-Oveisi** [comment]
Added some code to generate clean-up visualizations:
![image](https://github.com/GriffithsLab/whobpyt/assets/89212381/cec59107-e1aa-4506-a1d6-28039e8c0c49)
![image](https://github.com/GriffithsLab/whobpyt/assets/89212381/48fd0a57-b3fb-4467-b5b8-f4e63e0ac71f)
![image](https://github.com/GriffithsLab/whobpyt/assets/89212381/35cf378d-1f42-4153-8420-331805e59072)


However, having issues when trying to build the html files:
```

Extension error:
Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/external/rprshnas01/netdata_kcni/jglab/MemberSpaces/po/lab/repos/whobpyt_po_fork/examples/eg004r__fitting_JR_example.py failed leaving traceback:
Traceback (most recent call last):
  File "/external/rprshnas01/netdata_kcni/jglab/MemberSpaces/po/lab/repos/whobpyt_po_fork/examples/eg004r__fitting_JR_example.py", line 58, in <module>
    eeg_data_all = np.load(eeg_file)
  File "/external/rprshnas01/netdata_kcni/jglab/MemberSpaces/po/lab/envs/whobpyt/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../Tepit/eeg_data.npy'
```


Which seems to happen because the example data is being downloaded from a gdrive which doesn't have public access:
![image](https://github.com/GriffithsLab/whobpyt/assets/89212381/e073c4b9-f48f-4cd0-b361-22c5b9d32bd6)

I think the folder is owned by @JohnWangDataAnalyst . Can you adjust the access please?
